# Generated by Django 4.0.3 on 2022-03-17 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('weather', models.CharField(blank=True, choices=[('C', 'Cold'), ('H', 'Hot'), ('M', 'Mild')], max_length=1, null=True)),
                ('s_class', models.CharField(blank=True, choices=[('U', 'Upper'), ('M', 'Middle'), ('L', 'Lower')], max_length=1, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('nature', models.CharField(blank=True, choices=[('N', 'Neutral'), ('C', 'Chaotic')], max_length=1, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hungerGGG.distrito')),
            ],
        ),
    ]
