# Generated by Django 4.0.3 on 2022-03-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungerGGG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
            ],
        ),
        migrations.RenameModel(
            old_name='Distrito',
            new_name='District',
        ),
        migrations.RenameModel(
            old_name='Tributo',
            new_name='Tribute',
        ),
    ]
