# Generated by Django 4.0.3 on 2022-04-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungerGGG', '0002_game_session_rename_distrito_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_session',
            name='tributes',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tribute',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game_session',
            name='name',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
